decrypt:
  npmrc: repo/npmrc.asc
install: |-
  npm config set color false
  npm install
release:
  script: |-
    node --version
    npm -version
    npm test
    sed -i "s/0.0.0/${tag}/g" package.json
    chmod 600 ../npmrc
    npm publish --userconfig=../npmrc
merge:
  script: |-
    npm test
deploy:
  script: |-
    echo 'Nothing to deploy'
    exit -1
