docker:
  image: yegor256/rultor-image:1.19.0
assets:
  npmrc: yegor256/home#assets/npmrc
install: |-
  npm config set color false
  npm install
release:
  script: |-
    node --version
    npm -version
    npm test
    sed -i "s/0.0.0/${tag}/g" package.json
    chmod 600 ../npmrc
    npm publish --userconfig=../npmrc
merge:
  script: |-
    npm test
